using System.Globalization;
using System.Text;
using DeepField.Sim;
using DeepField.Sim.Content;
using DeepField.Sim.Util;

// Golden vectors for the Unreal port of WavePlan.cs (see README.md). Everything float is written
// as its IEEE-754 bit pattern so the C++ side compares bits, never decimal round-trips.

const uint Seed = 20260906u;                 // the gate-baseline seed
int[] playerCounts = { 1, 2, 4 };
const int EndlessExtra = 6;                  // waves planned past the authored arc (crosses a lap on testlane)
string[] mapOrder = { "testlane", "foundry", "switchyard", "spire", "toaster" };

string outPath = args.Length > 0 ? args[0] : "DFWavePlanGolden.inl";
var sb = new StringBuilder();
var inv = CultureInfo.InvariantCulture;

static uint Bits(float f) => BitConverter.SingleToUInt32Bits(f);
static string Hex(uint u) => "0x" + u.ToString("X8") + "u";

sb.AppendLine("// GENERATED by tools/waveplan-golden from sim/Sim.Core (frozen, ADR-0005). Do not edit by hand.");
sb.AppendLine("// Floats are IEEE-754 bit patterns. Included only by DFWavePlanTests.cpp, inside its anonymous namespace.");
sb.AppendLine();
sb.AppendLine($"static const uint32 GGoldenSeed = {Seed}u;");
sb.AppendLine();

// --- Balance dials the plan reads -------------------------------------------------------------
sb.AppendLine("static const FGoldenBalance GGoldenBalance = {");
sb.AppendLine($"\t{Hex(Bits(Balance.CountScalePerExtraPlayer))}, {Hex(Bits(Balance.HpScalePerExtraPlayer))}, {Hex(Bits(Balance.EndlessCountGrowthPerLap))},");
sb.AppendLine($"\t{Hex(Bits(Balance.HpGrowth))}, {Hex(Bits(Balance.EndlessHpGrowth))}, {Hex(Bits(Balance.BountyScale))}, {Hex(Bits(Balance.BountyGrowth))}, {Hex(Bits(Balance.ScrapGrowth))}");
sb.AppendLine("};");
sb.AppendLine();

// --- The sim's tables, frozen -----------------------------------------------------------------
var usedEnemies = new SortedSet<string>(StringComparer.Ordinal);
sb.AppendLine("// map, waveIndex, enemyId, count, spacingTicks, startDelayTicks, routeId");
sb.AppendLine("static const FGoldenGroup GGoldenGroups[] = {");
foreach (var mapId in mapOrder)
{
    var tables = Waves.ByMap[mapId];
    for (int w = 0; w < tables.Count; w++)
        foreach (var g in tables[w])
        {
            usedEnemies.Add(g.EnemyId);
            sb.AppendLine($"\t{{ \"{mapId}\", {w}, \"{g.EnemyId}\", {g.Count}, {g.SpacingTicks}, {g.StartDelayTicks}, \"{g.RouteId}\" }},");
        }
}
sb.AppendLine("};");
sb.AppendLine();

sb.AppendLine("// enemyId, scatterWidth bits, stealth, splitCount");
sb.AppendLine("static const FGoldenEnemy GGoldenEnemies[] = {");
foreach (var id in usedEnemies)
{
    var e = Enemies.All[id];
    sb.AppendLine($"\t{{ \"{id}\", {Hex(Bits(e.ScatterWidth))}, {(e.Stealth ? "true" : "false")}, {e.SplitCount} }},");
}
sb.AppendLine("};");
sb.AppendLine();

sb.AppendLine("// map, waveIndex, stealthWeightFactor bits (every scheduled condition, including the ones at 1.0)");
sb.AppendLine("static const FGoldenCondition GGoldenConditions[] = {");
foreach (var mapId in mapOrder)
{
    var map = Maps.All[mapId];
    for (int w = 0; w < Waves.ByMap[mapId].Count; w++)
        if (Conditions.ForWave(map, w) is { } c)
            sb.AppendLine($"\t{{ \"{mapId}\", {w}, {Hex(Bits(c.StealthWeightFactor))} }},   // {c.Id}");
}
sb.AppendLine("};");
sb.AppendLine();

// --- RNG --------------------------------------------------------------------------------------
sb.AppendLine("// seed, stream, index, first eight NextUInt() draws");
sb.AppendLine("static const FGoldenRng GGoldenRng[] = {");
foreach (var (seed, stream, index) in new (uint, string, uint)[]
{
    (Seed, RngStreams.Wave, 0u), (Seed, RngStreams.Wave, 7u), (Seed, RngStreams.Condition, 8u),
    (0u, RngStreams.Wave, 0u), (0xFFFFFFFFu, RngStreams.Spawn, 0xFFFFFFFFu), (1u, RngStreams.Combat, 300u),
})
{
    var rng = RngStreams.StreamFor(seed, stream, index);
    var draws = Enumerable.Range(0, 8).Select(_ => Hex(rng.NextUInt()));
    sb.AppendLine($"\t{{ {seed}u, \"{stream}\", {index}u, {{ {string.Join(", ", draws)} }} }},");
}
sb.AppendLine("};");
sb.AppendLine();

// NextFloat / NextInt share NextUInt; pin the conversions separately.
sb.AppendLine("// From StreamFor(seed, \"wave\", 3): alternating NextFloat() bits and NextInt(0, 7)");
{
    var rng = RngStreams.StreamFor(Seed, RngStreams.Wave, 3u);
    var parts = new List<string>();
    for (int i = 0; i < 6; i++)
    {
        parts.Add(Hex(Bits(rng.NextFloat())));
        parts.Add(rng.NextInt(0, 7).ToString(inv) + "u");
    }
    sb.AppendLine($"static const uint32 GGoldenFloatInt[] = {{ {string.Join(", ", parts)} }};");
}
sb.AppendLine();

// --- DetMath.PowInt ---------------------------------------------------------------------------
sb.AppendLine("// x bits, n, PowInt(x, n) bits");
sb.AppendLine("static const FGoldenPow GGoldenPow[] = {");
foreach (float x in new[] { Balance.HpGrowth, Balance.EndlessHpGrowth, Balance.EndlessCountGrowthPerLap, 0.5f, 3f })
    foreach (int n in new[] { 0, 1, 2, 3, 7, 9, 11, 12, 27, 40, -3 })
        sb.AppendLine($"\t{{ {Hex(Bits(x))}, {n}, {Hex(Bits(DetMath.PowInt(x, n)))} }},");
sb.AppendLine("};");
sb.AppendLine();

// --- MathF.Round ------------------------------------------------------------------------------
// No wave in the sim's tables lands a body count exactly on .5 (checked over four laps at 1/2/4
// players), so the plans above never exercise ties-to-even. These do: what .NET's MathF.Round —
// the call WavePlan.cs makes — returns for ties, near-ties and the counts a night wave produces.
sb.AppendLine("// x bits, MathF.Round(x) bits");
sb.AppendLine("static const FGoldenRound GGoldenRound[] = {");
{
    var inputs = new List<float> { 0.5f, 1.5f, 2.5f, 3.5f, 34.5f, 35.5f, 80.5f, -0.5f, -1.5f, -2.5f, 2.4f, 2.6f, 7f, 0f };
    foreach (float below in new[] { 0.5f, 2.5f, 34.5f })
    {
        inputs.Add(MathF.BitDecrement(below));
        inputs.Add(MathF.BitIncrement(below));
    }
    for (int count = 1; count <= 9; count++) inputs.Add(count * 0.5f);          // night: authored stealth count x (1.5 - 1)
    foreach (int count in new[] { 10, 30, 50, 70 }) inputs.Add(count * Balance.EndlessCountGrowthPerLap);   // a lap: 30 x 1.15f is 34.5 exactly
    foreach (float x in inputs)
        sb.AppendLine($"\t{{ {Hex(Bits(x))}, {Hex(Bits(MathF.Round(x)))} }},");
}
sb.AppendLine("};");
sb.AppendLine();

// --- Scales -----------------------------------------------------------------------------------
sb.AppendLine("// map, waveIndex, players, HpScale bits, BountyScale bits, ScrapScale bits");
sb.AppendLine("static const FGoldenScale GGoldenScales[] = {");
foreach (var mapId in mapOrder)
{
    var map = Maps.All[mapId];
    int authored = Waves.ByMap[mapId].Count;
    foreach (int w in new[] { 0, 1, authored - 1, authored, authored + 1, authored + 15 })
        foreach (int p in playerCounts)
            sb.AppendLine($"\t{{ \"{mapId}\", {w}, {p}, {Hex(Bits(WavePlan.HpScale(map, w, p)))}, {Hex(Bits(WavePlan.BountyScale(w)))}, {Hex(Bits(WavePlan.ScrapScale(w)))} }},");
}
sb.AppendLine("};");
sb.AppendLine();

// --- Plans ------------------------------------------------------------------------------------
// Ids are compared and hashed lower-cased. On the Unreal side they are FNames, which are
// case-insensitive, and in a Game build FName::ToString() returns whichever spelling was registered
// first in the process ("escape" comes back as "Escape" because InputCore got there first) — so the
// only key that is a function of the id alone is a case-folded one.
static string Key(string id) => id.ToLowerInvariant();

static int Canonical(SpawnEntry a, SpawnEntry b, MapDef map)
{
    if (a.TickOffset != b.TickOffset) return a.TickOffset.CompareTo(b.TickOffset);
    int c = string.CompareOrdinal(Key(a.DefId), Key(b.DefId));
    if (c != 0) return c;
    c = string.CompareOrdinal(Key(map.Routes[a.RouteIndex].Id), Key(map.Routes[b.RouteIndex].Id));
    if (c != 0) return c;
    c = Bits(a.LateralOffset).CompareTo(Bits(b.LateralOffset));
    if (c != 0) return c;
    return Bits(a.HpFactor).CompareTo(Bits(b.HpFactor));
}

static uint HashPlan(List<SpawnEntry> entries, MapDef map)
{
    uint h = 2166136261u;
    void Byte(uint b) { h ^= b & 0xFFu; h = unchecked(h * 16777619u); }
    void U32(uint v) { for (int i = 0; i < 4; i++) Byte(v >> (i * 8)); }
    void Str(string s) { foreach (char ch in Key(s)) Byte(ch); Byte(0); }
    foreach (var e in entries)
    {
        Str(e.DefId);
        U32(unchecked((uint)e.TickOffset));
        U32(Bits(e.HpFactor));
        Str(map.Routes[e.RouteIndex].Id);
        U32(Bits(e.LateralOffset));
    }
    return h;
}

sb.AppendLine("// map, waveIndex, players, entry count, FNV-1a of the plan in canonical order (ids lower-cased)");
sb.AppendLine("static const FGoldenPlan GGoldenPlans[] = {");
int planCount = 0;
foreach (var mapId in mapOrder)
{
    var map = Maps.All[mapId];
    int authored = Waves.ByMap[mapId].Count;
    for (int w = 0; w < authored + EndlessExtra; w++)
    {
        // The sim indexes the authored tables with the raw wave index when a condition is
        // scheduled, so a scheduled wave past the arc would throw; none is authored there.
        foreach (int p in playerCounts)
        {
            var plan = WavePlan.PlanWave(Seed, map, w, p);
            plan.Sort((a, b) => Canonical(a, b, map));
            sb.AppendLine($"\t{{ \"{mapId}\", {w}, {p}, {plan.Count}, {Hex(HashPlan(plan, map))} }},");
            planCount++;
        }
    }
}
sb.AppendLine("};");
sb.AppendLine();

// Whole plans spelled out, so a hash mismatch has something readable next to it: a scatter wave
// (motes draw laterals), and a night wave with authored stealth (the condition stream).
void Spell(string name, string mapId, int wave, int players)
{
    var map = Maps.All[mapId];
    var plan = WavePlan.PlanWave(Seed, map, wave, players);
    plan.Sort((a, b) => Canonical(a, b, map));
    sb.AppendLine($"// {mapId} wave {wave}, {players}p, canonical order: defId, tick, hp bits, routeId, lateral bits");
    sb.AppendLine($"static const FGoldenEntry {name}[] = {{");
    foreach (var e in plan)
        sb.AppendLine($"\t{{ \"{e.DefId}\", {e.TickOffset}, {Hex(Bits(e.HpFactor))}, \"{map.Routes[e.RouteIndex].Id}\", {Hex(Bits(e.LateralOffset))} }},");
    sb.AppendLine("};");
    sb.AppendLine();
}

int scatterWave = -1, stealthNightWave = -1;
string stealthNightMap = "";
{
    var foundry = Waves.ByMap["foundry"];
    for (int w = 0; w < foundry.Count && scatterWave < 0; w++)
        if (foundry[w].Any(g => Enemies.All[g.EnemyId].ScatterWidth > 0f)) scatterWave = w;
    foreach (var mapId in mapOrder)
    {
        var map = Maps.All[mapId];
        for (int w = 0; w < Waves.ByMap[mapId].Count && stealthNightWave < 0; w++)
            if (Conditions.ForWave(map, w) is { StealthWeightFactor: > 1f }
                && Waves.ByMap[mapId][w].Any(g => Enemies.All[g.EnemyId].Stealth))
            { stealthNightWave = w; stealthNightMap = mapId; }
    }
}
if (scatterWave < 0) throw new InvalidOperationException("foundry has no scatter wave to spell out");
if (stealthNightWave < 0) throw new InvalidOperationException("no map has authored stealth on a stealth-weighted wave");

sb.AppendLine($"static const TCHAR* GGoldenScatterMap = TEXT(\"foundry\"); static const int32 GGoldenScatterWave = {scatterWave}; static const int32 GGoldenScatterPlayers = 2;");
Spell("GGoldenScatterPlan", "foundry", scatterWave, 2);
sb.AppendLine($"static const TCHAR* GGoldenNightMap = TEXT(\"{stealthNightMap}\"); static const int32 GGoldenNightWave = {stealthNightWave}; static const int32 GGoldenNightPlayers = 1;");
Spell("GGoldenNightPlan", stealthNightMap, stealthNightWave, 1);

File.WriteAllText(outPath, sb.ToString().Replace("\r\n", "\n"));
Console.WriteLine($"wrote {outPath}: {planCount} plans, scatter wave foundry/{scatterWave}, night wave {stealthNightMap}/{stealthNightWave}");
